## Example usage to pull a particular data source

In [1]:
import os
from os.path import join as oj

In [2]:
# data source of interest
data_source = "chrr_health"

In [3]:
# current working directory
cur_dir = os.getcwd()

In [4]:
# raw data directory
raw_dir = oj(cur_dir, "county_level", "raw", data_source)

In [5]:
# processed data directory
processed_dir = oj(cur_dir, "county_level", "processed", data_source)

### 1. Download Data

In [6]:
os.chdir(raw_dir)  # changing directories to download data to raw data source folder
import download
os.chdir(cur_dir)  # changing directories back to original folder

Raw data is downloaded in data/county_level/raw/\<data source\> folder

### 2. Load Data

In [7]:
# loading raw data
from county_level.raw.chrr_health.load import load_chrr_health  # more generally: from county_level.raw.<data_source>.load import load_<data_source>
raw = load_chrr_health(data_dir = raw_dir)
raw.head()

,FIPS,Years of Potential Life Lost Rate,% Fair or Poor Health,Average Number of Physically Unhealthy Days,Average Number of Mentally Unhealthy Days,% Low Birthweight,% Smokers,% Adults with Obesity,Food Environment Index,% Physically Inactive,...,Income Ratio,% Single-Parent Households,Social Association Rate,Violent Crime Rate,Injury Death Rate,Average Daily PM2.5,Presence of Water Violation,% Severe Housing Problems,% Drive Alone to Work,% Long Commute - Drives Alone
0,1000,9942.794666,22.028703,4.918052,4.939753,10.254871,20.927353,35.5,5.8,29.8,...,5.261136,37.342739,12.371924,479.919182,82.250245,11.0,NaN,14.340702,85.794745,34.3
1,1001,8128.591190,20.882987,4.743889,4.654031,8.619529,18.081557,33.3,7.2,34.7,...,5.234597,26.242679,12.071202,272.282220,68.526994,11.7,No,14.663462,86.523661,39.6
2,1003,7354.122530,17.509134,4.224519,4.304056,8.345003,17.489033,31.0,8.0,26.5,...,4.417767,24.139601,10.205617,203.660396,72.385054,10.3,No,13.566201,84.282433,41.7
3,1005,10253.573403,29.591802,5.430279,5.185594,11.474559,21.999985,41.7,5.6,23.5,...,5.681410,56.603426,7.518797,414.277861,70.274612,11.5,No,14.583333,83.368470,32.2
4,1007,11977.539484,19.439724,4.591482,4.551699,10.308710,19.114200,37.6,7.8,33.5,...,4.368581,28.689236,8.381860,89.349126,108.156028,11.2,No,10.496454,84.910647,49.8

In [8]:
# loading cleaned data
from county_level.processed.chrr_health.clean import clean_chrr_health  # more generally: from county_level.processed.<data_source>.clean import clean_<data_source>
cleaned = clean_chrr_health(data_dir = raw_dir, out_dir = processed_dir)
cleaned.head()

,countyFIPS,Years of Potential Life Lost Rate,% Fair or Poor Health,Average Number of Physically Unhealthy Days,Average Number of Mentally Unhealthy Days,% Low Birthweight,Smokers_Percentage,% Adults with Obesity,Food Environment Index,% Physically Inactive,...,Income Ratio,% Single-Parent Households,Social Association Rate,Violent Crime Rate,Injury Death Rate,Average Daily PM2.5,Presence of Water Violation,% Severe Housing Problems,% Drive Alone to Work,% Long Commute - Drives Alone
0,01000,9942.794666,22.028703,4.918052,4.939753,10.254871,20.927353,35.5,5.8,29.8,...,5.261136,37.342739,12.371924,479.919182,82.250245,11.0,NaN,14.340702,85.794745,34.3
1,01001,8128.591190,20.882987,4.743889,4.654031,8.619529,18.081557,33.3,7.2,34.7,...,5.234597,26.242679,12.071202,272.282220,68.526994,11.7,0.0,14.663462,86.523661,39.6
2,01003,7354.122530,17.509134,4.224519,4.304056,8.345003,17.489033,31.0,8.0,26.5,...,4.417767,24.139601,10.205617,203.660396,72.385054,10.3,0.0,13.566201,84.282433,41.7
3,01005,10253.573403,29.591802,5.430279,5.185594,11.474559,21.999985,41.7,5.6,23.5,...,5.681410,56.603426,7.518797,414.277861,70.274612,11.5,0.0,14.583333,83.368470,32.2
4,01007,11977.539484,19.439724,4.591482,4.551699,10.308710,19.114200,37.6,7.8,33.5,...,4.368581,28.689236,8.381860,89.349126,108.156028,11.2,0.0,10.496454,84.910647,49.8